//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empolyee
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string EmployeeId { get; set; }
        public string Comment { get; set; }
    }
}
